server:
  port: 8082

jwt:
  secret:
    key: MY-SECRET-KEY
    validity: 36000000

spring:

  #datasource
  datasource:
    url: jdbc:h2:file:/home/rasoul/web/core-db;AUTO_SERVER=TRUE
    username: user
    password: 1234
    driver-class-name: org.h2.Driver

  #jpa & hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
  application:
    name: SSO
